# Generated by Django 6.1.1 on 2026-09-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=60, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('usage_type', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['plant_name'],
            },
        ),
    ]
